# permissions for end users to edit metals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: metal-editor-role
rules:
- apiGroups:
  - webapp.my.domain
  resources:
  - metals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.my.domain
  resources:
  - metals/status
  verbs:
  - get
